CREATE TABLE "CITESEER"."RESULT_MATCH80" 
   (	"DBLP_ID" NUMBER, 
	"CITESEER_ID" NUMBER, 
	"DBLP_TITLE" VARCHAR2(4000 BYTE), 
	"CITESEER_TITLE" VARCHAR2(4000 BYTE), 
	"TITLE_JWS" NUMBER DEFAULT 0, 
	"CITESEER_AUTHOR" VARCHAR2(4000 BYTE) NULL, 
	"CITESEER_AUTHOR_LEFT" VARCHAR2(4000 BYTE) NULL, 
	"DBLP_AUTHOR" VARCHAR2(4000 BYTE), 
	"AUTHOR_JWS" NUMBER DEFAULT 0, 
	"AUTHOR_JWS_LEFT" NUMBER DEFAULT 0
   );

--Join the papers that have a similarity higher than 80
INSERT INTO "CITESEER"."RESULT_MATCH80"(DBLP_ID, CITESEER_ID, DBLP_TITLE, CITESEER_TITLE, TITLE_JWS) 
SELECT dp.ID AS DBLP_ID,
       cp.ID AS CITESEER_ID,
       dp.TITLE AS DBLP_TITLE,
       cp.TITLE || '.' AS CITESEER_TITLE,
        UTL_MATCH.jaro_winkler_similarity (        TRIM(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(SUBSTR(dp.TITLE, 1, LENGTH(dp.TITLE) - 1)),'.: ',''),chr(38) ||'quot;',''),'et al.',''),'in:','')), TRIM(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(cp.TITLE),'.: ',''),chr(38) ||'quot;',''),'et al.',''),'in:',''))) AS jws       
FROM   AERCS_TT.PAPER dp, PAPER cp, AERCS_TT.AUTHOR_MEDIA dam, AUTHOR_PAPER cap, AERCS_TT.AUTHOR da, AUTHOR ca
WHERE  dp.ID > (SELECT MAX(DBLP_ID) FROM AERCS_TT.PAPER_MAPPING)
       AND dp.ID = dam.MEDIA_ID
       AND dam.AUTHOR_ID = da.ID
       AND cp.ID = cap.PAPER_ID
       AND cap.AUTHOR_ID = ca.ID
       AND  UTL_MATCH.jaro_winkler_similarity (        TRIM(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(SUBSTR(dp.TITLE, 1, LENGTH(dp.TITLE) - 1)),'.: ',''),chr(38) ||'quot;',''),'et al.',''),'in:','')), TRIM(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(cp.TITLE),'.: ',''),chr(38) ||'quot;',''),'et al.',''),'in:',''))) > 80;


INSERT INTO "CITESEER"."RESULT_MATCH80"(DBLP_ID, CITESEER_ID, DBLP_TITLE, CITESEER_TITLE, TITLE_JWS) 
SELECT dp.ID AS DBLP_ID,
       cp.ID AS CITESEER_ID,
       dp.TITLE AS DBLP_TITLE,
       cp.TITLE || '.' AS CITESEER_TITLE,
        UTL_MATCH.jaro_winkler_similarity (        TRIM(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(SUBSTR(dp.TITLE, 1, LENGTH(dp.TITLE) - 1)),'.: ',''),chr(38) ||'quot;',''),'et al.',''),'in:','')), TRIM(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(cp.TITLE),'.: ',''),chr(38) ||'quot;',''),'et al.',''),'in:',''))) AS jws       
FROM   AERCS_TT.PAPER dp, PAPER cp, AERCS_TT.AUTHOR_MEDIA dam, AUTHOR_PAPER cap, AERCS_TT.AUTHOR da, AUTHOR ca
WHERE  dp.ID < (SELECT MAX(DBLP_ID) FROM AERCS_TT.PAPER_MAPPING)
       AND cp.ID > (SELECT MAX(CITESEER_ID) FROM AERCS_TT.PAPER_MAPPING)
       AND dp.ID = dam.MEDIA_ID
       AND dam.AUTHOR_ID = da.ID
       AND cp.ID = cap.PAPER_ID
       AND cap.AUTHOR_ID = ca.ID
       AND  UTL_MATCH.jaro_winkler_similarity (        TRIM(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(SUBSTR(dp.TITLE, 1, LENGTH(dp.TITLE) - 1)),'.: ',''),chr(38) ||'quot;',''),'et al.',''),'in:','')), TRIM(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(cp.TITLE),'.: ',''),chr(38) ||'quot;',''),'et al.',''),'in:',''))) > 80;


--Merge DBLP authors' names into RESULT_MATCH80
MERGE INTO RESULT_MATCH80 A
USING (
SELECT max(AM.MEDIA_ID) as DBLP_ID,
LISTAGG(TRIM(LOWER(SUBSTR(AU.NAME,INSTR (AU.NAME, ' ', -1)))), '') WITHIN GROUP (ORDER BY TRIM(LOWER(SUBSTR(AU.NAME,INSTR (AU.NAME, ' ', -1))))) as DBLP_AUTHOR
FROM AERCS_TT.AUTHOR_MEDIA AM
    INNER JOIN AERCS_TT.AUTHOR AU
               ON AM.AUTHOR_ID = AU.ID 
WHERE AM.MEDIA_ID IN (SELECT DISTINCT DBLP_ID FROM RESULT_MATCH80)
GROUP BY AM.MEDIA_ID
) DA
ON (A.DBLP_ID = DA.DBLP_ID)
WHEN MATCHED THEN UPDATE SET A.DBLP_AUTHOR = DA.DBLP_AUTHOR;

--Merge Citeseer authors' names into RESULT_MATCH80
MERGE INTO RESULT_MATCH80 A
USING 
( 
SELECT max(AP.PAPER_ID) as CITESEER_ID,
LISTAGG(TRIM(LOWER(SUBSTR(AU.NAME,INSTR (AU.NAME, ' ', -1)))), '') WITHIN GROUP (ORDER BY TRIM(LOWER(SUBSTR(AU.NAME,INSTR (AU.NAME, ' ', -1))))) as CITESEER_AUTHOR,
LISTAGG(TRIM(LOWER(SUBSTR(AU.NAME,1,INSTR (AU.NAME, ' ', 1)))), '') WITHIN GROUP (ORDER BY TRIM(LOWER(SUBSTR(AU.NAME,1,INSTR (AU.NAME, ' ', 1))))) as CITESEER_AUTHOR_LEFT
FROM CITESEER.AUTHOR_PAPER AP 
    INNER JOIN CITESEER.AUTHOR AU
               ON AP.AUTHOR_ID = AU.ID 
WHERE AP.PAPER_ID IN (SELECT DISTINCT CITESEER_ID FROM RESULT_MATCH80)
GROUP BY AP.PAPER_ID
)CA
ON (A.CITESEER_ID = CA.CITESEER_ID)
WHEN MATCHED THEN UPDATE SET A.CITESEER_AUTHOR = CA.CITESEER_AUTHOR, A.CITESEER_AUTHOR_LEFT = CA.CITESEER_AUTHOR_LEFT;

--Compute the similarity between the DBLP and Citeseer authors' names
UPDATE RESULT_MATCH80
SET AUTHOR_JWS = UTL_MATCH.jaro_winkler_similarity (DBLP_AUTHOR,CITESEER_AUTHOR),
    AUTHOR_JWS_LEFT = UTL_MATCH.jaro_winkler_similarity (DBLP_AUTHOR,CITESEER_AUTHOR_LEFT);



--started 9:31PM 30/7/2017
--end of execution

SELECT *
FROM RESULT_MATCH80
WHERE ((AUTHOR_JWS BETWEEN 85 AND 100) OR (AUTHOR_JWS_LEFT BETWEEN 85 AND 100))
      AND TITLE_JWS < 90
UNION
SELECT *
FROM RESULT_MATCH80
WHERE (AUTHOR_JWS >= 75 OR AUTHOR_JWS_LEFT >=75 )
      AND TITLE_JWS >= 90
UNION
SELECT *
FROM RESULT_MATCH80
WHERE (AUTHOR_JWS >= 60 OR AUTHOR_JWS_LEFT >=60 )
      AND TITLE_JWS >= 95;

/*
DROP TABLE RESULT_MATCH80;
*/



