--Join the papers that have a similarity higher than 80
CREATE TABLE RESULT_MATCH80 as
SELECT dp.ID AS DBLP_ID,
       cp.ID AS CITESEER_ID,
       dp.TITLE AS DBLP_TITLE,
       cp.TITLE || '.' AS CITESEER_TITLE,
       UTL_MATCH.jaro_winkler_similarity(LOWER(dp.TITLE),LOWER(cp.TITLE || '.')) AS jws
FROM   AERCS_TT.PAPER dp, PAPER cp
WHERE  dp.TITLE like 'X%'
       AND cp.TITLE like 'X%'
       AND UTL_MATCH.jaro_winkler_similarity(LOWER(dp.TITLE),LOWER(cp.TITLE || '.')) > 80;

--Create a new table where the similiraty of authors' names will be put
CREATE TABLE "CITESEER"."RESULT_MATCH80_AUTHOR" 
   (	"DBLP_ID" NUMBER, 
	"CITESEER_ID" NUMBER, 
	"DBLP_TITLE" VARCHAR2(1000 BYTE), 
	"CITESEER_TITLE" VARCHAR2(4000 BYTE), 
	"TITLE_JWS" NUMBER, 
	"CITESEER_AUTHOR" VARCHAR2(4000 BYTE), 
	"CITESEER_AUTHOR_LEFT" VARCHAR2(4000 BYTE), 
	"DBLP_AUTHOR" VARCHAR2(4000 BYTE), 
	"AUTHOR_JWS" NUMBER, 
	"AUTHOR_JWS_LEFT" NUMBER
   );

--Copy recorcs from RESULT_MATCH80 to RESULT_MATCH80_AUTHOR
INSERT INTO "CITESEER"."RESULT_MATCH80_AUTHOR" 
SELECT rm.DBLP_ID as DBLP_ID,
       rm.CITESEER_ID as CITESEER_ID,
       rm.DBLP_TITLE as DBLP_TITLE,
       rm.CITESEER_TITLE as CITESEER_TITLE,
       jws as TITLE_JWS,
       '/' as CITESEER_AUTHOR,
       '*' as CITESEER_AUTHOR_LEFT,
       '-' as DBLP_AUTHOR,
       0 as AUTHOR_JWS,
       0 as AUTHOR_JWS_LEFT
FROM RESULT_MATCH80 rm;

--Concatenate authors' names' from Citeseer
CREATE TABLE RESULT_MATCH80_AUTHOR_CA AS
SELECT max(AP.PAPER_ID) as CITESEER_ID,
LISTAGG(TRIM(LOWER(SUBSTR(AU.NAME,INSTR (AU.NAME, ' ', -1)))), '') WITHIN GROUP (ORDER BY TRIM(LOWER(SUBSTR(AU.NAME,INSTR (AU.NAME, ' ', -1))))) as CITESEER_AUTHOR,
LISTAGG(TRIM(LOWER(SUBSTR(AU.NAME,1,INSTR (AU.NAME, ' ', 1)))), '') WITHIN GROUP (ORDER BY TRIM(LOWER(SUBSTR(AU.NAME,1,INSTR (AU.NAME, ' ', 1))))) as CITESEER_AUTHOR_LEFT
FROM CITESEER.AUTHOR_PAPER AP 
    INNER JOIN CITESEER.AUTHOR AU
               ON AP.AUTHOR_ID = AU.ID 
WHERE AP.PAPER_ID IN (SELECT DISTINCT CITESEER_ID FROM RESULT_MATCH80)
GROUP BY AP.PAPER_ID;

--Concatenate authors' names' from DBLP
CREATE TABLE RESULT_MATCH80_AUTHOR_DA AS
SELECT max(AM.MEDIA_ID) as DBLP_ID,
LISTAGG(TRIM(LOWER(SUBSTR(A.NAME,INSTR (A.NAME, ' ', -1)))), '') WITHIN GROUP (ORDER BY TRIM(LOWER(SUBSTR(A.NAME,INSTR (A.NAME, ' ', -1))))) as DBLP_AUTHOR
FROM AERCS_TT.AUTHOR_MEDIA AM
    INNER JOIN AERCS_TT.AUTHOR A
               ON AM.AUTHOR_ID = A.ID 
WHERE AM.MEDIA_ID IN (SELECT DISTINCT DBLP_ID FROM RESULT_MATCH80)
GROUP BY AM.MEDIA_ID;

--Merge DBLP authors' names into RESULT_MATCH80_AUTHOR
MERGE INTO RESULT_MATCH80_AUTHOR A
USING RESULT_MATCH80_AUTHOR_DA DA
ON (A.DBLP_ID = DA.DBLP_ID)
WHEN MATCHED THEN UPDATE SET A.DBLP_AUTHOR = DA.DBLP_AUTHOR;

--Merge Citeseer authors' names into RESULT_MATCH80_AUTHOR
MERGE INTO RESULT_MATCH80_AUTHOR A
USING RESULT_MATCH80_AUTHOR_CA CA
ON (A.CITESEER_ID = CA.CITESEER_ID)
WHEN MATCHED THEN UPDATE SET A.CITESEER_AUTHOR = CA.CITESEER_AUTHOR, A.CITESEER_AUTHOR_LEFT = CA.CITESEER_AUTHOR_LEFT;

--Compute the similarity between the DBLP and Citeseer authors' names
UPDATE RESULT_MATCH80_AUTHOR
SET AUTHOR_JWS = UTL_MATCH.jaro_winkler_similarity(DBLP_AUTHOR,CITESEER_AUTHOR),
    AUTHOR_JWS_LEFT = UTL_MATCH.jaro_winkler_similarity(DBLP_AUTHOR,CITESEER_AUTHOR_LEFT);

SELECT *
FROM RESULT_MATCH80_AUTHOR
WHERE ((AUTHOR_JWS BETWEEN 85 AND 100) OR (AUTHOR_JWS_LEFT BETWEEN 85 AND 100))
      AND TITLE_JWS < 90
UNION
SELECT *
FROM RESULT_MATCH80_AUTHOR
WHERE (AUTHOR_JWS >= 75 OR AUTHOR_JWS_LEFT >=75 )
      AND TITLE_JWS >= 90
UNION
SELECT *
FROM RESULT_MATCH80_AUTHOR
WHERE (AUTHOR_JWS >= 60 OR AUTHOR_JWS_LEFT >=60 )
      AND TITLE_JWS >= 95;

/*
DROP TABLE RESULT_MATCH80_AUTHOR;
DROP TABLE RESULT_MATCH80_AUTHOR_DA;
DROP TABLE RESULT_MATCH80_AUTHOR_CA;
DROP TABLE RESULT_MATCH80;
*/

SELECT MAX(DBLP_ID),COUNT(DBLP_ID) 
FROM RESULT_MATCH80_AUTHOR
GROUP BY DBLP_ID
ORDER BY COUNT(DBLP_ID) DESC

SELECT MAX("COUNT(DBLP_ID)") NUMBER_OF_MATCHES, COUNT("COUNT(DBLP_ID)") NUMBER_OF_PAPERS
FROM 
(
SELECT MAX(DBLP_ID),COUNT(DBLP_ID) 
FROM (SELECT *
FROM RESULT_MATCH80_AUTHOR
WHERE ((AUTHOR_JWS BETWEEN 85 AND 100) OR (AUTHOR_JWS_LEFT BETWEEN 85 AND 100))
      AND TITLE_JWS < 90
UNION
SELECT *
FROM RESULT_MATCH80_AUTHOR
WHERE (AUTHOR_JWS >= 75 OR AUTHOR_JWS_LEFT >=75 )
      AND TITLE_JWS >= 90
UNION
SELECT *
FROM RESULT_MATCH80_AUTHOR
WHERE (AUTHOR_JWS >= 60 OR AUTHOR_JWS_LEFT >=60 )
      AND TITLE_JWS >= 95) P
GROUP BY DBLP_ID
ORDER BY COUNT(DBLP_ID) DESC
) l
GROUP BY "COUNT(DBLP_ID)"
ORDER BY COUNT("COUNT(DBLP_ID)") DESC
